(function (lib, img, cjs) {

var p; // shortcut to reference prototypes

// stage content:
(lib.JUPT0002_Pnetwork_728x90_h4 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// timeline functions:
	this.frame_179 = function() {
		if (! this.alreadyExecuted)
		{
			this.alreadyExecuted = true;
			this.loopNum = 1;
		}
		else
		{
			this.loopNum++;
			if (this.loopNum == 3)
			{
				this.stop();
			}
		}
	}

	// actions tween:
	this.timeline.addTween(cjs.Tween.get(this).wait(179).call(this.frame_179));

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f().s("#91989C").ss(2,1,1).p("EA44AHCMhxvAAAIAAuDMBxvAAAg");
	this.shape.setTransform(364,45);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape}]}).wait(180));

	// out2
	this.instance = new lib.out2();
	this.instance.setTransform(171.2,62.5,1.065,1.064,0,0,0,136.4,65);

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(84).to({alpha:0},14).to({_off:true},7).wait(75));

	// FlashAICB
	this.instance_1 = new lib.Symbol13();
	this.instance_1.setTransform(125.3,34.2);
	this.instance_1.alpha = 0;
	this.instance_1._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(99).to({_off:false},0).to({x:147.1,alpha:1},13).wait(68));

	// jupiter logo
	this.instance_2 = new lib.jupiter_logo("synched",0);
	this.instance_2.setTransform(659.5,35,1,1,0,0,0,50.1,26.2);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.instance_2}]}).wait(180));

	// footer text
	this.instance_3 = new lib._728_dis();

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.instance_3}]}).wait(180));

	// white bg
	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("Eg43ABuIAAjaMBxvAAAIAADag");
	this.shape_1.setTransform(364,79);

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.shape_1}]}).wait(180));

	// Layer 3
	this.instance_4 = new lib._728x90_img();

	this.timeline.addTween(cjs.Tween.get({}).to({state:[{t:this.instance_4}]}).wait(180));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,728,90.5);


// symbols:
(lib._728_dis = function() {
	this.initialize(img._728_dis);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,728,90);


(lib._728x90_img = function() {
	this.initialize(img._728x90_img);
}).prototype = p = new cjs.Bitmap();
p.nominalBounds = new cjs.Rectangle(0,0,728,90);


(lib.Symbol13 = function() {
	this.initialize();

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("Aggg3IBBA3IhBA4g");
	this.shape.setTransform(79.7,0,1.165,1.165);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#053E6D").s().p("AAJAkIAAgeQAAgIgJAAQgIAAAAAIIAAAeIgQAAIAAhHIAQAAIAAAaQAEgHAJAAQAUAAAAAUIAAAgg");
	this.shape_1.setTransform(60,6.6,1.165,1.165);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#053E6D").s().p("AgIAkIAAglIgHAAIAAgOIAHAAIAAgUIAMAAIAAAUIANAAIAAAOIgNAAIAAAlg");
	this.shape_2.setTransform(54.3,6.6,1.165,1.165);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#053E6D").s().p("AAJAaIgJgcIgIAcIgNAAIgRgzIAPAAIAJAcIAJgcIAKAAIAJAcIAKgcIAOAAIgQAzg");
	this.shape_3.setTransform(47.5,7.8,1.165,1.165);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#053E6D").s().p("AgUAUQgIgJAAgLQAAgKAIgIQAJgJALAAQALAAAKAJQAIAIAAAKQAAALgIAJQgKAIgLAAQgLAAgJgIgAgJgIQgEAEAAAEQAAAFAEAEQAFAEAEAAQAFAAAEgEQAEgEAAgFQAAgEgEgEQgEgEgFAAQgEAAgFAEg");
	this.shape_4.setTransform(39.5,7.8,1.165,1.165);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#053E6D").s().p("AgQAbIAAg0IAQAAIAAAIQABgJAMAAIAEABIAAAOIgFAAQgMAAAAAMIAAAag");
	this.shape_5.setTransform(33.7,7.7,1.165,1.165);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#053E6D").s().p("AgWAbQgMgLAAgQQAAgPAMgLQALgLAPABQARgBALAMIgKAKQgHgHgLABQgIgBgHAHQgHAGAAAJQAAAJAHAHQAHAHAIAAQAJAAAHgGIAAgKIgTAAIAAgMIAiAAIAAAcQgLAOgUAAQgPAAgLgKg");
	this.shape_6.setTransform(26.3,6.6,1.165,1.165);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#053E6D").s().p("AAKAbIAAgdQAAgKgKAAQgDAAgDADQgDADAAAFIAAAcIgPAAIAAg0IAPAAIAAAHQAEgIAKAAQAJAAAGAGQAFAGAAAKIAAAfg");
	this.shape_7.setTransform(13.7,7.7,1.165,1.165);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#053E6D").s().p("AgUATQgIgIAAgLQAAgKAIgIQAHgIAMAAQALAAACAIIAAgHIARAAIAAAzIgRAAIAAgHQgCAIgLAAQgMAAgHgIgAgIgIQgEAEAAAEQAAAFAEAEQAEAEAEAAQAFAAAFgEQADgEAAgFQAAgEgDgEQgFgEgFAAQgEAAgEAEg");
	this.shape_8.setTransform(6.1,7.8,1.165,1.165);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#053E6D").s().p("AgTAUQgIgIAAgMIAAAAQAAgLAJgIQAIgHAKAAQAMAAAIAIQAIAHAAALIgBAEIgmAAQAAAEAEADQAEADAEAAQAIAAAFgFIAKAJQgKAJgNAAQgLAAgJgHgAgLgFIAXAAQAAgDgEgDQgDgCgFAAQgKAAgBAIg");
	this.shape_9.setTransform(-1.1,7.8,1.165,1.165);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#053E6D").s().p("AgcAlIAAhIIAQAAIAAAHQACgIAMAAQALAAAIAIQAIAIgBAMQABAKgIAHQgIAIgLAAQgMAAgCgIIAAAcgAgJgSQgEAEAAAGQAAAFAEADQAEADAFAAQAEAAAEgDQAFgDAAgFQAAgFgFgFQgEgDgEAAQgFAAgEADg");
	this.shape_10.setTransform(-8.4,8.9,1.165,1.165);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#053E6D").s().p("AgUAUQgIgJAAgLQAAgKAIgIQAJgJALAAQAMAAAIAJQAJAIAAAKQAAALgJAJQgIAIgMAAQgLAAgJgIgAgIgIQgFAEAAAEQAAAFAFAEQADAEAFAAQAGAAAEgEQADgEAAgFQAAgEgDgEQgEgEgGAAQgFAAgDAEg");
	this.shape_11.setTransform(-16.2,7.8,1.165,1.165);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#053E6D").s().p("AgQAbIAAg0IAQAAIAAAIQACgJALAAIAEABIAAAOIgFAAQgMAAAAAMIAAAag");
	this.shape_12.setTransform(-22.1,7.7,1.165,1.165);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.f("#053E6D").s().p("AgQAWQgIgHAAgLIAAgeIAQAAIAAAdQAAAJAIABQAJgBAAgJIAAgdIAQAAIAAAeQAAALgHAHQgHAFgLAAQgKAAgGgFg");
	this.shape_13.setTransform(-28.3,7.9,1.165,1.165);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#053E6D").s().p("AgYAkIAAhHIAwAAIAAAOIggAAIAAAOIAeAAIAAANIgeAAIAAAPIAhAAIAAAPg");
	this.shape_14.setTransform(-35.3,6.6,1.165,1.165);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#053E6D").s().p("AgQAbIAAg0IAQAAIAAAIQABgJAMAAIAEABIAAAOIgFAAQgMAAAAAMIAAAag");
	this.shape_15.setTransform(-45.8,7.7,1.165,1.165);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#053E6D").s().p("AgTAUQgHgIAAgMIAAAAQAAgLAHgIQAIgHALAAQAMAAAIAIQAIAHAAALIgBAEIgmAAQABAKALAAQAHAAAGgFIAJAJQgJAJgNAAQgLAAgJgHgAgLgFIAXAAQgBgDgDgDQgDgCgFAAQgKAAgBAIg");
	this.shape_16.setTransform(-52,7.8,1.165,1.165);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#053E6D").s().p("AgIAkIAAglIgIAAIAAgOIAIAAIAAgUIANAAIAAAUIAMAAIAAAOIgMAAIAAAlg");
	this.shape_17.setTransform(-57.5,6.6,1.165,1.165);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#053E6D").s().p("AgHAlIAAgzIAOAAIAAAzgAgFgVQgDgDAAgDQABgJAHAAQAIAAAAAJQAAADgCADQgDACgDAAQgCAAgDgCg");
	this.shape_18.setTransform(-61.2,6.5,1.165,1.165);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#053E6D").s().p("AgcAlIAAhIIAQAAIAAAHQADgIALAAQALAAAIAIQAIAIAAAMQAAAKgIAHQgIAIgLAAQgLAAgDgIIAAAcgAgJgSQgEAEAAAGQAAAFAEADQAEADAFAAQAEAAAEgDQAFgDAAgFQAAgFgFgFQgEgDgEAAQgFAAgEADg");
	this.shape_19.setTransform(-66.5,8.9,1.165,1.165);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#053E6D").s().p("AgRAWQgHgHAAgLIAAgeIAQAAIAAAdQAAAJAIABQAJgBAAgJIAAgdIAQAAIAAAeQAAALgHAHQgIAFgKAAQgKAAgHgFg");
	this.shape_20.setTransform(-74,7.9,1.165,1.165);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#053E6D").s().p("AgOAkIAAgPIAGABQAIAAAAgLIAAgvIAPAAIAAAuQAAANgDAGQgFAIgNAAIgIgBg");
	this.shape_21.setTransform(-80.1,6.7,1.165,1.165);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#FFFFFF").s().p("AgIAkIAAgnIgGAAIAAgMIAGAAIAAgUIAMAAIAAAUIALAAIAAAMIgLAAIAAAng");
	this.shape_22.setTransform(46.2,-8.1,1.165,1.165);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#FFFFFF").s().p("AgPAVQgIgGAAgLIAAgeIANAAIAAAdQAAAMAKAAQALAAAAgMIAAgdIANAAIAAAeQAAALgHAGQgHAGgKAAQgJAAgGgGg");
	this.shape_23.setTransform(40.7,-6.8,1.165,1.165);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#FFFFFF").s().p("AgTAUQgJgJAAgLQAAgKAJgJQAIgHALAAQALAAAJAHQAJAJAAAKQAAALgJAJQgJAHgLABQgLgBgIgHgAgKgLQgFAGAAAFQAAAHAFAEQAEAFAGAAQAHAAAEgFQAFgEAAgHQAAgFgFgGQgEgEgHAAQgGAAgEAEg");
	this.shape_24.setTransform(33.5,-6.9,1.165,1.165);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#FFFFFF").s().p("AgOAcIAAAHIgNAAIAAhHIANAAIAAAcQADgJAMAAQALAAAIAIQAIAJAAAJQAAALgIAJQgIAIgLAAQgMAAgDgJgAgKgBQgFADAAAHQAAAHAFAFQAEAEAGAAQAGAAAFgEQAEgFAAgHQAAgHgEgDQgFgFgGAAQgGAAgEAFg");
	this.shape_25.setTransform(26.1,-8,1.165,1.165);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.f("#FFFFFF").s().p("AgTAUQgIgJABgLQgBgKAIgJQAIgHALAAQAMAAADAJIAAgIIANAAIAAAzIgNAAIAAgHQgDAIgMABQgLgBgIgHgAgJgLQgFAGAAAFQAAAHAFAEQAEAFAFAAQAGAAAFgFQAFgEAAgHQAAgFgFgGQgFgEgGAAQgFAAgEAEg");
	this.shape_26.setTransform(18.3,-6.9,1.165,1.165);

	this.shape_27 = new cjs.Shape();
	this.shape_27.graphics.f("#FFFFFF").s().p("AgRAUQgJgHABgNIAAAAQgBgLAJgIQAHgIALABQALAAAIAHQAHAIAAALIAAADIgoAAQABAOANAAQAIgBAHgFIAHAHQgKAKgMAAQgLAAgHgIgAgIgNQgEAEgBAFIAbAAQAAgFgEgEQgEgDgFAAQgEAAgFADg");
	this.shape_27.setTransform(6.2,-6.9,1.165,1.165);

	this.shape_28 = new cjs.Shape();
	this.shape_28.graphics.f("#FFFFFF").s().p("AgPAaIAAgzIANAAIAAAIQACgJAMAAIAEAAIAAANIgGgBQgGABgEAEQgCADAAAGIAAAag");
	this.shape_28.setTransform(0.8,-6.9,1.165,1.165);

	this.shape_29 = new cjs.Shape();
	this.shape_29.graphics.f("#FFFFFF").s().p("AgTAUQgIgJAAgLQAAgKAIgJQAIgHALAAQALAAAJAHQAJAJgBAKQABALgJAJQgJAHgLABQgLgBgIgHgAgKgLQgFAGAAAFQAAAHAFAEQAFAFAFAAQAHAAAEgFQAFgEAAgHQAAgFgFgGQgEgEgHAAQgFAAgFAEg");
	this.shape_29.setTransform(-5.4,-6.9,1.165,1.165);

	this.shape_30 = new cjs.Shape();
	this.shape_30.graphics.f("#FFFFFF").s().p("AAaAaIAAgcQAAgNgKAAQgLAAAAANIAAAcIgKAAIAAgcQAAgNgJAAQgFAAgDAEQgDADAAAGIAAAcIgNAAIAAgzIANAAIAAAIQAFgJAJAAQALAAACAJQAEgJAOAAQAJABAEAFQAGAGAAAJIAAAfg");
	this.shape_30.setTransform(-14.2,-6.9,1.165,1.165);

	this.shape_31 = new cjs.Shape();
	this.shape_31.graphics.f("#FFFFFF").s().p("AgHAkIAAgnIgHAAIAAgMIAHAAIAAgUIALAAIAAAUIALAAIAAAMIgLAAIAAAng");
	this.shape_31.setTransform(-26.4,-8.1,1.165,1.165);

	this.shape_32 = new cjs.Shape();
	this.shape_32.graphics.f("#FFFFFF").s().p("AgQAVQgHgGAAgLIAAgeIANAAIAAAdQAAAMAKAAQALAAAAgMIAAgdIANAAIAAAeQAAALgHAGQgHAGgKAAQgJAAgHgGg");
	this.shape_32.setTransform(-31.8,-6.8,1.165,1.165);

	this.shape_33 = new cjs.Shape();
	this.shape_33.graphics.f("#FFFFFF").s().p("AgTAUQgJgJAAgLQAAgKAJgJQAIgHALAAQAMAAAIAHQAJAJAAAKQAAALgJAJQgIAHgMABQgLgBgIgHgAgKgLQgFAGAAAFQAAAHAFAEQAEAFAGAAQAGAAAFgFQAFgEAAgHQAAgFgFgGQgFgEgGAAQgGAAgEAEg");
	this.shape_33.setTransform(-39,-6.9,1.165,1.165);

	this.shape_34 = new cjs.Shape();
	this.shape_34.graphics.f("#FFFFFF").s().p("AgTAdQgIgIAAgMQAAgJAIgJQAIgIALAAQAMAAADAJIAAgcIANAAIAABHIgNAAIAAgHQgDAJgMAAQgLAAgIgIgAgJgBQgFADAAAHQAAAHAFAFQAEAEAFAAQAHAAAEgEQAFgFAAgHQAAgHgFgDQgEgFgHAAQgFAAgEAFg");
	this.shape_34.setTransform(-51.6,-8,1.165,1.165);

	this.shape_35 = new cjs.Shape();
	this.shape_35.graphics.f("#FFFFFF").s().p("AALAaIAAgcQAAgNgLAAQgLAAAAANIAAAcIgMAAIAAgzIAMAAIAAAIQAFgJAJAAQAVABAAAUIAAAfg");
	this.shape_35.setTransform(-58.7,-6.9,1.165,1.165);

	this.shape_36 = new cjs.Shape();
	this.shape_36.graphics.f("#FFFFFF").s().p("AgFAlIAAgzIALAAIAAAzgAgGgcQAAgDADgCQACgDABAAQACAAADADQACACAAADQAAAHgHAAQgGAAAAgHg");
	this.shape_36.setTransform(-63.6,-8.1,1.165,1.165);

	this.shape_37 = new cjs.Shape();
	this.shape_37.graphics.f("#FFFFFF").s().p("AgVAkIAAhHIArAAIAAAMIgeAAIAAASIAbAAIAAAKIgbAAIAAAfg");
	this.shape_37.setTransform(-68.1,-8.1,1.165,1.165);

	this.shape_38 = new cjs.Shape();
	this.shape_38.graphics.f("#ED7E23").s().p("AsZCoQgYAAgRgRQgRgSAAgYIAAjZQAAgYARgRQARgSAYAAIYzAAQAXAAASASQARARAAAYIAADZQAAAYgRASQgSARgXAAg");
	this.shape_38.setTransform(0,0,1.165,1.165);

	this.addChild(this.shape_38,this.shape_37,this.shape_36,this.shape_35,this.shape_34,this.shape_33,this.shape_32,this.shape_31,this.shape_30,this.shape_29,this.shape_28,this.shape_27,this.shape_26,this.shape_25,this.shape_24,this.shape_23,this.shape_22,this.shape_21,this.shape_20,this.shape_19,this.shape_18,this.shape_17,this.shape_16,this.shape_15,this.shape_14,this.shape_13,this.shape_12,this.shape_11,this.shape_10,this.shape_9,this.shape_8,this.shape_7,this.shape_6,this.shape_5,this.shape_4,this.shape_3,this.shape_2,this.shape_1,this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-99.2,-19.5,198.6,39.2);


(lib.Symbol11 = function() {
	this.initialize();

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AhbCPIAAkdIC1AAIAAAuIiCAAIAABFIB5AAIAAAsIh5AAIAABPICEAAIAAAvg");

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-9.2,-14.2,18.6,28.7);


(lib.Symbol10 = function() {
	this.initialize();

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("ABRCPIiZjJIAADJIgyAAIAAkdIAtAAICWDFIAAjFIAyAAIAAEdg");

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-12.3,-14.2,24.7,28.7);


(lib.Symbol9 = function() {
	this.initialize();

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgYCPIAAkdIAxAAIAAEdg");

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-2.5,-14.2,5.2,28.7);


(lib.Symbol8 = function() {
	this.initialize();

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("ABFCPIAAiBIiIAAIAACBIg0AAIAAkdIA0AAIAABwICIAAIAAhwIAzAAIAAEdg");

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-11.9,-14.2,24.1,28.7);


(lib.Symbol7 = function() {
	this.initialize();

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AggCPQgQgEgOgJQgPgJgKgMQgKgMgHgPIAngYQAEAKAIAIQAHAIAJAGQAJAGALACQALAEALAAQAOAAAKgEQAJgEAGgFQAKgLAAgOQgBgJgDgHQgFgHgIgGQgLgHgdgMIgggPQgQgFgLgKQgLgKgGgNQgHgOAAgTQABgQAGgPQAIgOAMgLQAMgKAQgGQARgFAPAAQAQAAAPAEQANADALAGQALAGAIAKQAJAHAGALIgkAZQgJgNgMgGQgMgHgTABQgOgBgMAJQgLAJAAANQAAAJAEAHQAFAGAIAFIAuAVQAVAIANAIQAPAHAJAKQAKAKAEANQAFANAAAQQAAASgHAQQgFAPgNAMQgNALgTAHQgTAGgYAAQgTAAgSgFg");

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-10.5,-14.8,21.1,29.7);


(lib.Symbol6 = function() {
	this.initialize();

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgYCPIAAjvIhOAAIAAguIDNAAIAAAuIhNAAIAADvg");

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-10.3,-14.2,20.7,28.7);


(lib.Symbol5 = function() {
	this.initialize();

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgsCKQgWgIgPgOQgIgHgGgJQgHgIgEgLQgEgLgDgNQgCgMAAgPIAAiuIA0AAIAACqQAAASAEAPQAFANAJAJQAIAJAMAFQAMADANAAQAPAAALgDQAMgFAIgJQAJgJAFgNQAEgPAAgSIAAiqIA0AAIAACuQAAAPgCAMQgDANgEALQgEALgHAIQgGAJgIAHQgPAOgWAIQgVAHgYAAQgXAAgVgHg");

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-11.6,-14.5,23.3,29.1);


(lib.Symbol4 = function() {
	this.initialize();

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgdCRQgPgDgOgFQgOgGgLgHQgNgIgKgKQgKgKgJgMQgIgMgFgNQgGgOgDgPQgDgPAAgPQAAgOADgPQADgPAGgNQAFgNAIgMQAJgMAKgLQAKgKANgIQALgHAOgGQAOgFAPgDQAPgEAOAAQAPAAAPAEQAPADAOAFQANAGAMAHQANAIAKAKQAKALAIAMQAJAMAGANQAFANADAPQADAPAAAOQAAAPgDAPQgDAPgFAOQgGANgJAMQgIAMgKAKQgKAKgNAIQgMAHgNAGQgOAFgPADQgPADgPABQgOgBgPgDgAgmhdQgTAIgOAOQgNAOgIATQgHASAAAUQAAAVAHATQAIASANAOQAOAOATAIQASAIAUgBQAVABASgIQATgIANgOQAOgOAHgSQAIgTAAgVQAAgUgIgSQgHgTgOgOQgNgOgTgIQgSgIgVAAQgUAAgSAIg");

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-15.1,-14.8,30.3,29.8);


(lib.Symbol3 = function() {
	this.initialize();

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AiDAtIAAgbIgCADIgCADIgFACIgFAAQgFAAgFgCQgEgCgDgDQgEgEgCgFQgBgEAAgGQAAgDABgFQACgFAEgEQADgDAEgCQAFgCAFAAIAFAAIAFACIACADIACADIAAgHIAMAAIAABEgAiWgMIgEADIgDAFIgBAEIABAGIADAFIAEADIAGABIAGgBIAEgDIADgFIABgGIgBgEIgDgFIgEgDIgGgBIgGABgAnfAtIAAhEIALAAIAAAHIABgDIADgDIAFgCIAGAAQAFAAAEACQAEACADADQAEAEABAFQACAFAAADQAAAGgCAEQgBAFgEAEQgDADgEACQgEACgFAAIgGAAIgFgCIgDgDIgBgDIAAAbgAnMgMIgFADIgDAFIgBAEIABAGIADAFIAFADIAFABIAFgBIAFgDIADgFIABgGIgBgEIgDgFIgFgDIgFgBIgFABgAMoAZQgFgCgEgEQgDgEgCgEIgCgFIAAgGIACgJQACgFADgDQAEgEAFgCQAEgCAGAAIAFABIAEABIAFADIAEAEIgHAIQgCgDgDgBQgDgCgDAAIgHABIgEAEIgDAFIgBAEIABAGIADAFIAEAEIAHABQADAAADgCIAFgEIAHAIIgEAEIgFADIgEABIgFABQgGAAgEgCgALUAaIgFgCIgFgEIgDgEIAIgGQABADADABQAEACAEAAQAEAAACgCQABAAAAgBQABAAAAAAQAAgBAAAAQAAgBAAAAIgBgDIgCgCIgJgDIgGgDIgDgBIgCgDIgBgGIABgGIAEgFIAFgDIAGgBQAEAAAFACQAEACACAEIgGAHIgDgDIgGgBIgEABQAAAAgBABQAAAAAAAAQAAABAAAAQAAABAAAAQAAABAAAAQAAABAAAAQABABAAAAQABABAAAAIAJAEIAGACIAEACIACAEIABAFIgBAGIgEAFQgCACgEABQgDACgGAAIgGgBgAKqAaIgGgCIgEgEIgCgEIAGgGQACADADABQAEACAEAAQAFAAABgCQABAAAAgBQABAAAAAAQAAgBAAAAQABgBAAAAIgBgDIgEgCIgJgDIgEgDIgEgBIgCgDIgBgGIABgGIAEgFIAFgDIAHgBQADAAAGACQADACACAEIgFAHIgEgDIgGgBIgEABQAAAAgBABQAAAAAAAAQAAABAAAAQgBABAAAAQAAABABAAQAAABAAAAQABABAAAAQABABAAAAIAJAEIAGACIAEACIACAEIABAFIgBAGIgEAFQgCACgDABQgFACgEAAIgHgBgAIuAZQgEgCgEgEQgDgEgCgEIgBgFIgBgGIACgJQACgFADgDQAEgEAEgCQAFgCAFAAIAGABIAEABIAFADIAEAEIgGAIQgDgDgDgBQgDgCgEAAIgFABIgFAEIgDAFIgBAEIABAGIADAFIAFAEIAFABQAEAAADgCIAGgEIAGAIIgEAEIgFADIgEABIgGABQgFAAgFgCgAFdAZQgFgCgDgEQgEgEgCgEIgCgFIAAgGIACgIQACgFAEgEQADgEAFgCIAKgCQAFAAAEACQAFACADAEQAEAEACAFIACAIIAAAGIgCAFQgCAEgEAEQgDAEgFACQgEACgFAAQgIgBgCgBgAFhgNIgFAEIgDAFIgBAEIABAGIADAFIAFAEIAGABIAGgBIAEgEIADgFIABgGIgBgEIgDgFIgEgEIgGgBIgGABgACeAZQgFgCgDgEQgEgEgCgEIgCgFIAAgGQAAgCACgGQACgFAEgEQADgEAFgCIAKgCQAFAAAFACQAEACAEAEQADAEACAFIACAIIAAAGIgCAFQgCAEgDAEQgEAEgEACQgFACgFAAQgIgBgCgBgACigNIgFAEIgDAFIgBAEIABAGIADAFIAFAEIAGABIAFgBIAFgEIADgFIABgGIgBgEIgDgFIgFgEIgFgBIgGABgABLAaIgFgCIgFgEIgDgEIAIgGQABADADABQADACAFAAQAEAAACgCQABAAAAgBQABAAAAAAQAAgBAAAAQAAgBAAAAIgBgDIgCgCIgJgDIgGgDIgDgBIgCgDIgBgGIABgGIAEgFIAFgDIAGgBQAEAAAFACQAEACACAEIgGAHIgDgDIgGgBIgEABQAAAAgBABQAAAAAAAAQAAABAAAAQAAABAAAAQAAABAAAAQAAABAAAAQABABAAAAQABABAAAAIAJAEIAGACIAEACIACAEIABAFIgBAGIgDAFQgDACgEABQgDACgGAAIgGgBgAhiAZIgHgEQgDgCgBgEQgBgEAAgGIAAgcIALAAIAAAbIAAAFIACAEIAEACIAEABIAEgBIADgCIACgEIABgFIAAgbIALAAIAAAcQAAAFgCAFQgBADgDADIgHAEQgEACgEAAQgFAAgEgCgAoLAZQgEgCgEgEQgEgEgCgEIgBgFIgBgGIACgIQACgFAEgEQAEgEAEgCIAKgCQAFAAAFACQAEACAEAEQADAEADAFIACAIIgBAGIgBAFQgDAEgDAEQgEAEgEACQgFACgFAAQgHgBgDgBgAoHgNIgEAEIgEAFIgBAEIABAGIAEAFIAEAEIAGABIAGgBIAEgEIADgFIACgGIgCgEIgDgFIgEgEIgGgBIgGABgApiAZIgHgEQgCgCgCgEQgCgEABgGIAAgcIAKAAIAAAbIABAFIACAEIAEACIAEABIAEgBIADgCIACgEIABgFIAAgbIAMAAIAAAcQgBAFgCAFQgBADgDADIgHAEQgEACgEAAQgEAAgFgCgAt1AZQgFgCgDgEQgEgEgCgEIgBgFIgBgGQAAgCACgGQACgFAEgEQADgEAFgCIAKgCQAFAAAFACQAEACAEAEQADAEACAFIACAIIgBAGIgBAFQgCAEgDAEQgEAEgEACQgFACgFAAQgIgBgCgBgAtxgNIgFAEIgDAFIgBAEIABAGIADAFIAFAEIAGABIAFgBIAFgEIADgFIABgGIgBgEIgDgFIgFgEIgFgBIgGABgAumAZQgFgCgDgEQgDgEgCgEIgCgFIgBgGIADgJQACgFADgDQADgEAFgCQAEgCAGAAIAFABIAFABIAFADIADAEIgGAIQgDgDgDgBQgCgCgEAAIgGABIgFAEIgCAFIgBAEIABAGIACAFIAFAEIAGABQAEAAACgCIAGgEIAGAIIgDAEIgFADIgFABIgFABQgGAAgEgCgAvVAaIgFgCIgEgEIgDgEIAHgGQACADADABQADACAFAAQAEAAACgCQAAAAABgBQAAAAAAAAQABgBAAAAQAAgBAAAAIgBgDIgDgCIgJgDIgFgDIgEgBIgCgDIgBgGIABgGIAFgFIAEgDIAHgBQAEAAAFACQAEACACAEIgGAHIgEgDIgFgBIgFABQAAAAAAABQAAAAgBAAQAAABAAAAQAAABAAAAQAAABAAAAQAAABABAAQAAABABAAQAAABABAAIAJAEIAFACIAFACIACAEIABAFIgBAGIgEAFQgDACgDABQgEACgFAAIgHgBgAQfAaQgFAAgFgBQgFgCgDgEQgDgDgCgFQgBgFAAgGIABgJQACgFADgDQADgEAFgCQAFgCAFAAQAFAAAEACQAFACADAEQADADACAFIABAJIAAADIgkAAIABAGIACAEIAFACIAFABQAFAAADgBIAGgFIAGAHIgFAFIgEADIgGABgAQrgDIgBgFIgDgDIgDgCIgFgBIgFABIgEACIgDADIgBAFIAZAAIAAAAgAPCAaIgEgCIgEgDIgBgDIAAAHIgLAAIAAhDIALAAIAAAaIABgDIAEgDIAEgCIAGAAQAFAAAEACQAEACAEADQADAEABAFQACAFAAADQAAAGgCAEQgBAFgDAEQgEADgEACQgEACgFAAIgGAAgAPBgMIgFADIgDAFIgBAEIABAGIADAFIAFADIAFABIAFgBIAFgDIADgFIABgGIgBgEIgDgFIgFgDIgFgBIgFABgANWAYQgDgCgEgDQgDgEgCgFQgBgEAAgGQAAgDABgFQACgFADgEQAEgDADgCQAFgCAFAAIAGAAIAEACIADADIACADIAAgHIALAAIAAAwIgLAAIAAgHIgCADIgDADIgEACIgGAAQgFAAgFgCgANcgMIgFADIgCAFIgBAEIABAGIACAFIAFADIAFABIAGgBIAEgDIAEgFIABgGIgBgEIgEgFQgBgCgDgBIgGgBIgFABgAJ0AYQgEgCgEgDQgCgEgCgFQgCgEAAgGQAAgDACgFQACgFACgEQAEgDAEgCQAFgCAFAAIAFAAIAEACIADADIADADIAAgHIALAAIAAAwIgLAAIAAgHIgDADIgDADIgEACIgFAAQgFAAgFgCgAJ6gMQgDABgCACIgDAFIgBAEIABAGIADAFIAFADIAFABIAGgBIAEgDIADgFIABgGIgBgEIgDgFIgEgDIgGgBIgFABgAHNAYQgEgCgDgDQgDgEgCgFQgCgEABgGQgBgDACgFQACgFADgEQADgDAEgCQAFgCAFAAIAFAAIAFACIADADIACADIAAgaIALAAIAABDIgLAAIAAgHIgCADIgDADIgFACIgFAAQgFAAgFgCgAHTgMQgDABgBACIgEAFIgBAEIABAGIAEAFIAEADIAGABIAFgBIAFgDIACgFIABgGIgBgEIgCgFIgFgDIgFgBIgGABgAAkAaQgGAAgEgBQgFgCgDgEQgEgDgBgFQgCgFAAgGIACgJQABgFAEgDQADgEAFgCQAEgCAFAAQAFAAAFACQAEACAEAEQACADACAFIACAJIAAADIglAAIABAGIADAEIAFACIAFABQAEAAADgBIAGgFIAGAHIgEAFIgFADIgFABgAAvgDIgBgFIgCgDIgEgCIgFgBIgEABIgFACIgCADIgCAFIAZAAIAAAAgAjGAaQgGAAgEgBQgFgCgDgEQgEgDgCgFQgBgFAAgGIABgJQACgFAEgDQADgEAFgCQAFgCAFAAQAEAAAFACQAEACAEAEQADADABAFIABAJIAAADIgkAAIABAGIADAEIAEACIAGABQAEAAAEgBIAFgFIAGAHIgEAFIgFADIgFABgAi7gDIgBgFIgCgDIgEgCIgEgBIgGABIgDACIgDADIgCAFIAZAAIAAAAgAllAYQgEgCgDgDQgDgEgCgFQgCgEABgGQgBgDACgFQACgFADgEQADgDAEgCQAFgCAFAAIAFAAIAFACIADADIACADIAAgHIALAAIAAAwIgLAAIAAgHIgCADIgDADIgFACIgFAAQgFAAgFgCgAlfgMIgFADIgDAFIgBAEIABAGIADAFIAFADIAGABIAFgBIAFgDIACgFIABgGIgBgEIgCgFIgFgDIgFgBIgGABgAmOAaQgGAAgFgBQgEgCgDgEQgEgDgCgFQgCgFABgGIABgJQACgFAEgDQADgEAEgCQAFgCAFAAQAFAAAFACQAEACADAEQADADABAFIACAJIAAADIglAAIABAGIAEAEIAEACIAGABQAEAAADgBIAFgFIAHAHIgFAFIgEADIgGABgAmDgDIgBgFIgCgDIgFgCIgEgBIgFABIgEACIgDADIgCAFIAaAAIAAAAgAsHAaQgFAAgFgBQgFgCgDgEQgEgDgCgFQgBgFAAgGIABgJQACgFAEgDQADgEAFgCQAEgCAGAAQAEAAAFACQAEACAEAEQADADABAFIABAJIAAADIgkAAIABAGIADAEIAEACIAGABQAEAAAEgBIAFgFIAGAHIgEAFIgFADIgFABgAr8gDIgBgFIgCgDIgEgCIgEgBIgGABIgDACIgEADIgBAFIAZAAIAAAAgAPnAZIAAgwIALAAIAAAHQACgEADgCIAEgCIAFAAIADAAIAAAMIgEgBIgGABIgDADIgDAEIgBAFIAAAZgAOYAZIAAgwIAMAAIAAAwgAODAZIAAhDIALAAIAABDgAJSAZIAAhDIALAAIAABDgAGtAZIAAhDIAKAAIAABDgAGJAZIAAgwIALAAIAAAHQABgEAEgCIAEgCIAFAAIADAAIAAAMIgFgBIgFABIgEADIgDAEIAAAFIAAAZgAEzAZIgJgeIgKAeIgJAAIgQgwIAMAAIAJAdIAKgdIAIAAIAKAdIAKgdIAKAAIgQAwgADNAZIAAglIgIAAIAAgLIAIAAIAAgDQAAgFABgEQABgDAEgDQADgDAIAAIAFABIAAAKIgEgBQgBAAgBAAQgBAAAAABQgBAAAAAAQgBAAAAABQgBACgBADIAAAEIAJAAIAAALIgJAAIAAAlgAgGAZIAAgwIAJAAIAAAwgAgiAZIAAglIgGAAIAAgLIAGAAIAAgTIALAAIAAATIALAAIAAALIgLAAIAAAlgAg6AZIAAgwIALAAIAAAwgAkXAZIAAgbIgBgFIgBgDIgEgDIgEAAIgFAAIgDADIgCAEIgBAEIAAAbIgLAAIAAgwIALAAIAAAHQABgEAEgCIAFgCIAEAAQAFAAADABIAGAEIADAHIABAIIAAAdgAo6AZIAAgwIALAAIAAAHQABgEAEgCIAFgCIAEAAIAEAAIAAAMIgGgBIgEABIgFADIgCAEIgBAFIAAAZgAqiAZIAAhDIAqAAIAAALIgeAAIAAAQIAcAAIAAAMIgcAAIAAARIAfAAIAAALgArpAZIAAgwIALAAIAAAHQACgEADgCIAEgCIAFAAIADAAIAAAMIgEgBIgGABIgDADIgDAEIgBAFIAAAZgAs9AZIgVgwIAMAAIANAgIAOggIALAAIgUAwgAvyAZIAAgwIALAAIAAAwgAw1AZIAAhDIAYAAIAHAAIAHACIAGADIAFAEIADAGIADAFIACAHIABAIIgBAHIgCAFIgDAGIgDAFIgFAEIgGADIgGACIgIAAgAwpAOIALAAIAKgCQAFgBADgEQACgDABgEQACgCAAgFQAAgGgCgEQgBgEgCgDQgDgEgFgBQgGgCgEAAIgLAAgAOagfQgDgCAAgDQAAgDADgCQAAgBABAAQAAAAABgBQAAAAABAAQAAAAABAAQABAAAAAAQABAAAAAAQABABAAAAQABAAABABQACACAAADQAAADgCACQgBAAgBABQAAAAgBAAQAAAAgBABQAAAAgBAAQgBAAAAAAQgBgBAAAAQgBAAAAAAQgBgBAAAAgAgFgfQgCgCAAgDQAAgDACgCQABgBAAAAQABAAAAgBQABAAAAAAQABAAABAAQAAAAAAAAQAAAAAAAAQAAABABAAQABAAAAABQACACAAADQAAADgCACQAAAAgBABQgBAAAAAAQAAAAAAABQAAAAAAAAQgBAAgBAAQAAgBgBAAQAAAAgBAAQAAgBgBAAgAg5gfQgCgCAAgDQAAgDACgCQAAgBABAAQABAAAAgBQABAAAAAAQABAAAAAAQABAAABAAQAAAAABAAQAAABABAAQAAAAABABQACACAAADQAAADgCACQgBAAAAABQgBAAAAAAQgBAAAAABQgBAAgBAAQAAAAgBAAQAAgBgBAAQAAAAgBAAQgBgBAAAAgAvxgfQgCgCAAgDQAAgDACgCQAAgBABAAQAAAAABgBQAAAAABAAQAAAAABAAQABAAAAAAQABAAAAAAQABABAAAAQABAAABABQABACAAADQAAADgBACQgBAAgBABQAAAAgBAAQAAAAgBABQAAAAgBAAQgBAAAAAAQgBgBAAAAQgBAAAAAAQgBgBAAAAg");
	this.shape.setTransform(0.1,0.9);

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(-107.7,-3.5,215.7,9.1);


(lib.jupiter_logo = function() {
	this.initialize();

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#FFFFFF").s().p("AgxAuQAAgBAAgBQAAAAAAgBQABAAAAgBQAAAAABAAIAJgDIAAglIgFAAQgBAAAAAAQgBAAAAgBQgBAAAAAAQgBgBAAAAIABgBQAAgBAAAAQAAAAABgBQAAAAABAAQAAAAABAAIAFAAIAAgfIgHAAQgBAAgBAAQAAgBgBAAQAAAAAAgBQAAgBAAgBQAAgEADAAIAfAAQABAAAAABQABAAAAAAQABABAAAAQAAABAAAAQAAAFgCAAIgIAAIAAAfIAGAAQADAAABADQAAAAgBAAQAAAAAAAAQAAAAAAABQgBAAAAAAIgDABIgFAAIAAAhIAIgCQABAAAAAAQABAAAAAAQABABAAAAQAAABABAAQAAABAAABQAAAAAAABQgBAAAAABQAAAAgBAAIgjAJIgBABQgBAAAAgBQAAAAgBAAQAAAAAAgBQAAAAAAgBgAgMAvQgBAAAAAAQgBAAAAAAQAAgBAAgBQAAAAAAgBQAAgBAAgBQAAAAAAgBQABAAABAAQAAgBABAAIATAAIAAgOIgPAAIgCgBIAAgDQAAAAAAgBQAAgBAAAAQAAgBABAAQAAAAABAAIAPAAIAAgPIgMAAQgFAAAAgEIAAgsQAFAAAGgDQAAAAABgBQAAAAAAAAQABABAAAAQAAAAAAABIAAAEQATgGALADQAKADAAAIIAAAiQAAAEgEAAIgPAAIAAAPIAPAAQABAAABAAQAAAAABABQAAAAAAABQABABAAAAQABAEgFAAIgPAAIAAAOIAWAAQAAAAABABQABAAAAAAQABABAAAAQAAABAAAAQAAAEgDAAgAAYgBIAFAAIAAgPIgFAAgAAEgBIAFAAIAAgPIgFAAgAAYgYIAFAAIAAgMQAAgDgFAAgAAEgjIAAALIAFAAIAAgMg");
	this.shape.setTransform(93.9,47.5);

	this.shape_1 = new cjs.Shape();
	this.shape_1.graphics.f("#FFFFFF").s().p("AghAwQgGAAAAgGIAAgiIgEAAQgBAAAAAAQgBAAAAAAQgBgBAAAAQAAgBAAAAIAAgRQAIAAAGgDQAAAAABAAQAAAAAAAAQAAAAABAAQAAABAAAAIABAEIAGgBQAKgCAGAAQgCgDABgCIABgBIAHgDIABgDIAEgBIAFgTQAKgBAEgBIADABIgBAEIAVAAQAAAAAAAAQABAAAAAAQAAABABAAQAAAAAAABIAAADQgBAAAAABQAAAAAAAAQgBAAAAAAQAAAAgBAAIgFAAIACAIQAFAAAAACQAAAAABABQAAAAAAABQAAAAAAAAQgBABAAAAQAAAAAAABQAAAAgBAAQAAAAAAABQgBAAAAAAIgEAAIgHAAQgEgBgCgCIgDgMIgCAAIgCAJQgCAGgEABIgKABIADAGIAcAAQAHAAACAEQABAFAAAJQAAAAAAAAQAAABAAAAQgBAAAAAAQAAAAgBAAIgIAAIAAAIQAAAFgFAAIg3AAIAAAHIAHgCIAQgBIAgAAQAFAAACAFQACADAAAKQAAAGgGAAgAgXAhIAAAIIAvAAIAAgIQAAgBAAAAQAAgBAAAAQgBAAAAAAQgBAAAAAAIgWAAQgMAAgLACgAgXAIIAAAFIArAAIAAgFQAAAAAAAAQAAgBAAAAQgBAAAAgBQAAAAgBAAIgXAAQgJAAgJACgAgXAAIAAACIARgCIAhAAIAEAAIAAgDQAAgBgBAAQAAAAAAgBQgBAAAAAAQAAAAgBAAIgjAAQgMAAgKADIAAACIAFAAIABAAgAgugTQAAAAgBAAQAAAAgBgBQAAAAAAgBQAAAAAAgBIACgDIADAAIAGgTQAGAAAIgCIACABIgBAEIAVAAIABADQAAAAAAAAQAAABAAAAQAAABAAAAQAAAAAAAAQAAABAAAAQAAAAAAABQgBAAAAAAQAAAAgBAAIgFAAIACAGQAFABAAACIAAADIgCACIgLAAQgDgBgEgDIgCgKIgBAAIgDAKQgCAGgFAAIgNgBg");
	this.shape_1.setTransform(78.9,47.3);

	this.shape_2 = new cjs.Shape();
	this.shape_2.graphics.f("#FFFFFF").s().p("AgtAyIgCgBIgCgDQAAgBABgBQAAAAAAgBQABAAAAAAQAAgBABAAIADAAIAAgvQAIgBAHgEIACABIAAAFIAEgCQAHgDAJAAIA1AAIADACIgBAEIgDABIgbAAIAAAKIAVAAIACADQAAAAAAABQAAAAAAABQAAAAAAABQAAAAgBAAIgBABIgVAAIAAAJIAWAAIADACQAAAAAAABQAAABAAAAQAAABAAAAQAAAAgBABIgBABIgXAAIAAAKIAcAAIACACQAAAAABABQAAAAAAABQAAAAAAABQgBAAAAAAQAAABAAAAQAAAAgBAAQAAABAAAAQgBAAAAAAIhJAAQAAAAAAAAQgBAAAAgBQAAAAgBAAQAAgBAAAAIgCACQgBABAAAAQAAAAgBAAQAAABgBAAQAAAAgBAAgAgaApIAcAAIAAgKIgUAAQgBAAAAAAQgBAAAAgBQgBAAAAAAQgBAAAAgBQAAAAAAAAQAAgBAAAAQAAgBAAAAQAAgBAAAAIADgCIAVAAIAAgJIgGAAQgCAFgDABQgDABgMAAIgCgCgAgaAAIAAAQQABgBAEAAIADgOQAGAAAJgBQAAAAAAAAQABAAAAAAQAAAAAAAAQAAAAAAABIgBAHIAFAAIAAgIQAHAAAHgCIgeAAQgHABgFABgAgdgKIgEgBQAAgBAAAAQgBAAAAgBQAAAAAAgBQAAAAABgBQAAAAAAgBQAAAAAAgBQABAAAAAAQABAAAAAAIAUAAIAEgCIgQgHQAAAAgBgBQAAAAAAAAQAAgBAAAAQABAAAAgBIAIgCIgZAAQAAAAgBAAQAAAAgBAAQAAgBAAAAQAAgBAAAAIAAgEIAEgBIAhAAIgDgGIAAgCIAGgBIAGgCQABAAAAAAQABAAAAAAQABABAAAAQAAABABABIAEAIIAiAAIADACIgBAEIgDABIgXAAIAHACQABABAAAAQAAAAAAABQAAAAAAAAQAAAAAAAAIgBABIgKAFIAKAEIANAAIACACIAAADIgCABIgdAAIgIgCIgHADgAAFgaIAIgEIgQgBg");
	this.shape_2.setTransform(64,47.3);

	this.shape_3 = new cjs.Shape();
	this.shape_3.graphics.f("#FFFFFF").s().p("AATAyQgEgBgDgFIgFgIIgMAAIgFAJQgEAEgEABIgaAAQgEgBAAgEIABgDIARAAIADgGIgJAAQAAAAgBAAQAAAAgBgBQAAAAAAAAQgBgBAAgBIAAgGIAAgcQALgBAEgCIACABIABADIAEgBIAOgCIAgAAQAGAAAEAFQABACABAEIAAAZIgDADIgLAAIAFAHIAPAAQAAAAABAAQAAAAAAABQABAAAAAAQAAABABAAIgBADQAAAAAAABQgBAAAAAAQAAAAgBAAQAAABAAAAgAgVAXIAAAGIAsAAIAAgGgAgWAQIAtAAIAAgEIgtAAgAgWAFIAAAAIAtAAQgBgCgEgBIgaAAQgIAAgGADgAAYgEQgHgBAAgGIgBgGIgCABIgDAHQgDAEgGAAIgUAAIgCgCQAAAAAAgBQAAAAAAgBQAAAAAAgBQAAAAAAgBQACgBAFAAIAFAAQAEAAABgDQADgGAEgNQAHABAIgCIACABIAAACIgDAHQAHgEAFACIADgHQAAgBAAAAQAAgBAAAAQgBgBAAAAQAAAAAAgBQgDgCgHABQgMAAgJADIgBAHQgBADgEAAIgLAAIgCgCQgBAAAAgBQAAAAAAgBQAAAAAAgBQAAgBABAAQABAAAAgBQABAAAAAAQABAAAAAAQAAAAABAAIAEgNQAIAAAEgCQABAAAAAAQABAAAAAAQAAAAAAABQAAAAAAABIgBAGQAHgEAMgCQALgBAHACQAGACACAEQABACAAAFIgCAGQAAABgBAAQAAAAAAABQAAAAAAAAQgBAAAAABIgGgCIgHAAIAAAMQABAAAAABQABAAAAAAQABAAAAAAQABABABAAIAIAAQABAAAAAAQABAAAAAAQAAAAAAABQABAAAAABQAAAAAAABQAAAAAAABQAAAAAAAAQAAABAAAAQgBAAAAABQAAAAgBAAQgBAAAAAAQgBABgBAAgAgfgFIgOAAIgDgCIABgEQAAAAAAAAQAAAAABgBQAAAAABAAQAAAAABAAIAEAAIADgLQAKgBAFgCIABABIAAACIgEAOQgBAEgEAAIgBAAgAgggdQgHAAAAgDIgFgNQAAgBAAAAQAAgBABAAQAAAAABAAQABAAABAAQADACAIgBIAFALIACAAQABAAAAABQABAAAAAAQAAABAAABQAAAAAAACIgCABg");
	this.shape_3.setTransform(49.2,47.4);

	this.shape_4 = new cjs.Shape();
	this.shape_4.graphics.f("#FFFFFF").s().p("AguAuIgBgBQgBAAAAgBQAAAAAAgBQAAAAAAgBQAAAAAAgBQAAAAABgBQAAAAAAAAQABgBAAAAQABAAAAAAIAoAAIAAgKIgUAAQgBAAgBgBQAAAAgBAAQAAAAAAgBQAAAAAAgBIgHABIgIAAIgDgCQAAAAAAgBQAAgBAAAAQAAgBAAAAQAAAAAAgBQAAAAABgBQAAAAABAAQAAAAABAAQABAAABAAIAIgUQAKAAAGgBQABAAAAAAQAAAAAAABQABAAAAAAQAAAAAAAAIgCAFIAMAAIAAgGQAIAAAGgCIgnAAQgHAAAAgGIAAggQAJgBAGgCQAAgBABAAQABAAAAAAQAAAAABAAQAAABAAABIAAAGQAHgGAQgBQANgBAMACQAGAAACAGQACACAAAFIAAAUQAAAHgHAAIgXAAIACACIAAAGIAcAAQAAAAAAAAQABAAAAAAQABABAAAAQAAABABABIAAACIgDACIgcAAIAAAKIAYAAQABAAABAAQAAAAABABQAAAAAAAAQABABAAAAIgBAEIgEABIgXAAIAAAKIAjAAQABAAAAAAQABABAAAAQABAAAAABQAAABAAABQAAABAAAAQAAABAAAAQgBABAAAAQgBAAAAAAgAgXAWIASAAIAAgKIgOAAgAgTgKIAoAAIAAgKIgoAAgAgTggIAAAFIAoAAIgBgGQgCgDgHgBIgGAAQgPAAgJAFg");
	this.shape_4.setTransform(34.3,47.3);

	this.shape_5 = new cjs.Shape();
	this.shape_5.graphics.f("#FFFFFF").s().p("AgFAxQgBAAAAAAQgBAAAAAAQAAAAgBgBQAAAAAAgBIAAhDIglAAQAAAAgBAAQAAAAgBAAQAAAAgBgBQAAAAAAgBQAAAAAAgBQAAAAAAgBQAAAAAAgBQAAAAABgBIAEgBIAjAAIAAgSQAIABAGgEQABAAAAAAQABAAAAAAQAAAAABAAQAAABAAAAIAAAUIAlAAQABAAAAABQABAAAAAAQAAAAABABQAAAAAAAAQAAABAAAAQAAABAAAAQAAABAAAAQAAABAAAAQAAAAgBABQAAAAAAAAQAAAAgBAAQAAAAgBAAIglAAIAABEIgCABgAAhArQgHgBgDgGIgEgRIgGghIABgCIAIACIAJAAIAJAxQABABAEAAQABAAABAAQAAAAABABQAAAAABAAQAAABAAAAIAAADQAAABgBAAQAAABAAAAQgBAAAAAAQgBAAAAAAIgKABIgDgBgAgtArQgBAAAAAAQAAAAgBgBQAAAAAAAAQAAgBgBAAQAAAAAAgBQAAAAAAAAQAAgBAAAAQAAgBAAAAQABgDAEABQAFAAAAgDIAEgXIAEgYQAHABAIgDIACABIABACIgKAxQgBAHgIAAg");
	this.shape_5.setTransform(19.4,47.4);

	this.shape_6 = new cjs.Shape();
	this.shape_6.graphics.f("#FFFFFF").s().p("AhDBFQgFAAgBgFQAAgEAHgBQAJgBADgEQABgDAAgMIAAhNQAAgMgBgCQgCgGgJgBQgHAAAAgEQAAgFAGAAIBPAAQASAAAKAHQANALAAAQQAAAPgMAJQgKAHgQACQAJAAAGAEQADAEAGAJIAOAcIAGAKQACAEAHABQAFACAAADQAAAEgHAAIglAAQgDAAgCgCIgCgFIgUgoIgIgRQgDgCgFAAQgBAAAAAAQgBABAAAAQgBAAAAAAQAAABgBAAIAAAGIAAAdQAAALACADQACAFAKABQAFACAAADQAAAFgDAAgAgRg3IAAApIABAHQABACAEAAQALAAAFgFQALgHAAgOQAAgMgHgIQgGgIgKAAQgIAAgCAEg");
	this.shape_6.setTransform(92.9,31.3);

	this.shape_7 = new cjs.Shape();
	this.shape_7.graphics.f("#FFFFFF").s().p("Ag4BFQgFAAAAgEQAAgFAFgBQALgBADgFQACgDAAgLIAAhMQgBgMgBgDQgDgGgJgBQgHAAAAgDQAAgGAFAAIBqAAQABAAABAAQAAABABAAQAAAAABABQAAAAAAABIAAAFIAAASIgBAFQAAAAAAABQAAAAgBAAQAAABgBAAQgBAAgBAAQgCAAgEgGIgLgMQgEgEgNAAQgPAAgCACQgDABABAJIAAAbQAAAGABACQABADADAAQAOAAAFgBQAHgCADgKQADgHAEAAQAEAAAAAFIAAAkQAAAHgFAAQgEAAgEgLQgEgKgOAAIgJAAQgEAAgBACIAAAHIAAAaQAAANADAFQADAHAMAAQAaAAAKgUQACgIAGAAQAEAAAAAFIgEAcQAAAEgDAAg");
	this.shape_7.setTransform(76.8,31.3);

	this.shape_8 = new cjs.Shape();
	this.shape_8.graphics.f("#FFFFFF").s().p("AgfBKQgGAAAAgFQAAgEAGgBQAKgBADgEQABgDAAgMIAAhbIAAgGQgBgBgFAAQgKAAgHAFQgFADgHAKQgGAIgDAAQgEAAAAgFIAIgeQACgIAEAAQADAAACADQABAFACAAIBTAAIAKAAQAEgBADgEQACgFADAAQAFAAgBAIIgDAdIgBAGQgBADgDAAQgFAAgCgHQgFgMgEgEQgFgEgNAAQgFAAAAABQgBABAAAFIAABbQAAALABADQACAFAKABQAHABAAAEQAAAFgGAAg");
	this.shape_8.setTransform(61.8,30.8);

	this.shape_9 = new cjs.Shape();
	this.shape_9.graphics.f("#FFFFFF").s().p("AgfBFQgGAAAAgFQAAgEAGgBQAKgBADgEQABgDAAgMIAAhMQAAgMgBgDQgCgGgKgBQgHAAAAgEQAAgFAGAAIA/AAQAGAAAAAFQAAAEgHAAQgKABgCAFQgBADAAANIAABMQAAALABADQACAFAKABQAHACAAADQAAAFgGAAg");
	this.shape_9.setTransform(49.5,31.3);

	this.shape_10 = new cjs.Shape();
	this.shape_10.graphics.f("#FFFFFF").s().p("Ag7BFQgGAAABgFQAAgEAFgBQALgBACgEQABgDABgMIAAhNQAAgMgBgCQgCgGgKgBQgHAAAAgEQAAgFAFAAIBKAAQAWAAALAIQARAKAAAVQAAAQgMANQgLAMgVAAIgQgDQgFgDgGAAQAAAAgBAAQAAAAAAAAQgBABAAAAQAAAAAAABIAAAEIAAAbQAAALABADQACAFAIABQAHABAAAEQAAAFgFAAgAgHg0QgBAEAAAPIAAAXQAAAHABABQAEACAGAAQANAAAHgIQAFgJAAgNQAAgLgHgJQgHgJgMAAQgHAAgCAHg");
	this.shape_10.setTransform(37.2,31.3);

	this.shape_11 = new cjs.Shape();
	this.shape_11.graphics.f("#FFFFFF").s().p("AgnA8QgMgHgEgKQgCgJAAgPIAAg5QAAgNgBgDQgDgFgKgCQgGAAAAgDQAAgFAEAAIBCAAQAFAAAAAFQABADgHAAQgKACgCAFQgCADABANIAAAuQAAAaADAJQAHARAWABQAVAAAKgNQAHgJAAgVIAAg2QAAgNgCgFQgCgFgKgCIgFAAQgEgBAAgCQAAgFAIAAIAoAAQAEAAAAAFQAAADgIAAQgHACgDAGIgBAQIAAA3QABAPgCAGQgDAKgIAIQgRANgbAAQgaAAgQgKg");
	this.shape_11.setTransform(21,31.5);

	this.shape_12 = new cjs.Shape();
	this.shape_12.graphics.f("#FFFFFF").s().p("AguBqQgIgGAAgJQAAgHAFgEQAEgFAHABQANAAAFANQADAIADAAQAHgBAEgKQADgKAAgVIAAiHQAAgMAAgDQgCgFgKgBQgHgCAAgDQAAgEAFAAIBAAAQAFAAAAAEQAAADgGACQgKABgCAFQgCACAAANIAABtQAAATgCAKQgEAMgKAMQgKAMgLAHQgQAKgMAAQgJAAgHgFg");
	this.shape_12.setTransform(5.6,31);

	this.shape_13 = new cjs.Shape();
	this.shape_13.graphics.rf(["#FFFFFF","#2B2B2A"],[0,1],-0.9,-1.1,0,-1.3,-1.2,4.2).s().p("AgMAXQgKgGgDgLQgCgIAFgKQAFgJALgDQAJgDAKAFQAJAGADAKQADAJgFAKQgGAJgLADIgGABQgGAAgGgDg");
	this.shape_13.setTransform(50,20);

	this.shape_14 = new cjs.Shape();
	this.shape_14.graphics.f("#BD373D").s().p("ABIBYQgDAAgEgEIgGgBQgBAAAAgBQgBAAAAAAQgBgBAAAAQgBAAgBAAQgHAAgHgGIgEgCIgSgCIgHgBIgGgEQgFgHgDgCIgLgFQgEgCAAgCIAAgCIACAAIAOAGIAFAEIAGADIAKADIANABIADAAIABAAIADAAIAAgBIgBAAIgCgBIAAAAIAAAAQgDAAgDgCIgFgEIgGAAQgFAAgHgHIgDgCQgEAAgFgCQgBAAAAAAQgBAAAAAAQgBgBAAAAQAAAAAAAAIACgBIALADIAFADQADAEAEgBQAEgBAHAEQACABAFAAIAHACIABABIAAAAIAFADIAGABIAHACIAEACIAFAAIAFAAQAAAAABAAQAAAAABAAQAAABABAAQAAAAABABQABAAAAAAQABAAAAABQABAAAAAAQABAAAAAAIgDgDQgHgDgEAAQgIgEgDgDIAAgBQgGABgCgBIgHgCIgFgDIgDgDIgKAAQgDAAgBgDQAAgBAAAAQgBAAAAgBQAAAAAAAAQgBAAAAAAIgEAAIgJgDQgCgBgEgBIgEgCQgDgCgEAAIgIgBQAAgBAAAAQgBAAAAAAQAAgBAAAAQAAgBAAgBIgCgDIgBgBQgHABgEgCIgBgDIgCgBQAAAAgBAAQAAAAAAAAQAAgBAAAAQAAAAAAAAIgCgBIgEgBQgHAAgCgCQgCgDgDgBIgIAAIgDAAIgDAAIgDgCQgBgCgEgBIgPAAIgEgCQgDgEgDAAIgLgBQgEABgCgBQgBgBAAAAQAAAAAAgBQAAAAABAAQAAAAAAAAIAKgBIAGAAIAGABQAFACABACQAAAAABAAQAAAAAAAAQABAAAAAAQAAAAABAAIADAAIAKABIADABQAAABAAAAQABABAAAAQABAAAAAAQABABABAAQAMgCAJACQADAAACAEIAAAAQADACAIgBIAGAAQAFABACABQADAEABAAIAPABIACABIAAABIAAABIgJABIgBABIABAAIAGABIAHAAIAIgBIAFgBIANAAIgBgBIgGgCIgOgGIgSgGIgCAAIgHgCIgFgBIgHgDQgFgBgDABIgGgCQgBAAAAgBQAAAAgBAAQAAAAgBAAQgBgBAAAAIgHgCIgIgBIgGgDIgFgCIgJgDIgRgEQgJgCgEgDIgDgBIAAgBQAAAAABAAQAAAAAAAAQABAAAAAAQAAAAAAABIAMACQACACAFABIAFABIAHACQAAAAAAAAQABAAAAAAQABAAABAAQAAAAABAAQADADAHABIAMAFQAFACAGgBQAGABADACIAGADQADAAAGABIAGACIAHABIACAAIAHAEIAMACIAJACQAFABACACIAEACQAFgBADACIABAAQABADAFgBQAEACAJACIAFADIAEAAIAOADIAHADIAEABIABgBIgBgFIgDgEIAAAAIgCgBIAAgBIgEgBQgDgBgEgBQgBAAgEAAIgEgDIgDAAIgHgDIgIgDIgEAAIgDgBQgGgEgDgBIgDgBIgEgCIgGAAIgFAAIgCgBQgBgBAAAAQAAAAgBgBQgBAAAAAAQgBAAgBAAIgEgBIgGgDIgKgDIgHgDQgFAAgEgCQgEAAgCgCIgBAAIgIgDIgJgEQgGgDgEABIgDgCIgLgDIgEgBQgFAAgCgCIgFAAIgDABQAAABgBAAQAAAAAAAAQgBAAAAgBQAAAAgBAAIgCgCIgDgBIgKgBIgBgBIAJgKIACABIAEAEQAEAEAJACQAAAAABAAQAAAAAAABQABAAAAAAQAAAAABAAIAIADIAHADQADAAACACIAFAAIAMAEQADACAHACIAEAAIADABQACABAFABQACACAEgBQABACAEAAIAEACIAEABIAEACQACgBAFADQADABAFAAQAEACAHACIAHACIAHAAIAGABQACADAFABIAFACIAHACQADAAAEACQADACAEgBIACACIABAAIABgCQAAgCgDgCIgBgCIgEgBIgDAAIgEgDIgCgBIgCgBIgHAAIgEAAIgDgBIgFgBIgGgDIgHgBIgMgEIgEgBIgEgCIgFgDQgFgCgDABIgFgCIgNgFIgGgBIAAgBIAJABQACABAFAAQACACAEAAIACABQACACADAAIAFAAIAGACIAIACQADgBAEADQABABAAAAQAAAAABAAQABAAAAAAQABABABAAQABAAAAAAQABAAAAAAQABABAAAAQABAAAAABIADAAIAEACQABAAAAAAQABAAAAAAQABABAAAAQABAAAAgBQADgBADADIAEACQAEAAADACIADABIADAAQADABAFgBIAIADQAEACABgEQABgBgIgBIgOgDQAAAAgBgBQAAAAgBAAQAAAAgBgBQAAAAgBAAIgEgBIgFgBIgEgCIgHgBIgBgBIgGgDIgFgCIgGAAIgHgEIgFgCQgDAAgDgCIgFgCQgEABgCgBIgCgBQgBABgCgBQgFgCgDABIgFgDIgIgDQgDgBgCABIgEgBQgFgBgCgEIgFgCIgGAAIgDgBIgEAAIgGgDQgDABgDgEQgEABgCgBQgBAAgBAAQAAAAgBAAQgBAAAAAAQAAgBgBAAIgBgDIgHAAIgBgCIgDAAIgBgCIAHgFIACABQAEAAABACIALADIAHACIAHABIAFADQADAAADABIAGACQAEgBACACQABAAAAAAQABAAAAAAQABABAAAAQABAAAAABIAGAAQADAAADACIAFACQADAAAFADIACAAQABACAEAAQABAAAAAAQABAAAAAAQABAAAAAAQABAAAAAAQAAgBgBAAQAAAAgBgBQAAAAgBAAQAAAAgBAAIgEgDIgDAAIgFgCQgEABgBgCIgGgCQgBgCgEgBIgFAAQgCgCgEAAIgDgBIgEAAIgEgCIgEAAQgEABgDgDIgDgDQgBABAAAAQAAAAgBAAQAAAAgBAAQgBgBAAAAQAAAAgBgBQAAAAgBAAQAAAAgBAAQAAgBgBAAIgEgBIgGgBIABgDIgBgBIgCgCIAEgBIAAgBQARgJAQgDIADACIABABQAAABgFAAIgFACIAEADQAFAAADABIACACIADAAIAJACIAJACQACADAEABQAFABAAACQAAABAAAAQAAABAAAAQAAAAAAABQAAAAAAABQAAAAgBAAQAAAAAAAAQgBAAAAAAQgBAAAAAAIgEABIgHgBQgBABgFgBQAAAAAAAAQgBAAAAAAQgBAAAAAAQgBAAgBAAIgGgFIAAgBIAJAAQAAAAAAAAQAAgBABAAQAAAAAAAAQAAAAABABIACAAIAEAAIgCgBIgCgCIgDAAIgDAAIgIABIgEABIgGgCQgDgEgFABIgHABIgJAAIgEACIACABIAEAAIAFAAIAEABIAEABQABACAEgCQABACAFgBIAEACIgBADQABABAEAAQAEABAHAAIAFABIACACIAFABQADABAFAAIABACQAAAAABAAQAAABAAAAQAAAAABAAQABABAAAAIAIABQACABACADIAHAFQAEACACADQACABADAAIAJAEIALAEQAFACAEAAIAKAEIAFACIAEACQAAAAABAAQAAAAABABQAAAAABAAQAAAAAAAAIABgBQgDgCgBgCIgBgCQgFgBgHgDIgCgCIgIgCQgEgDgCgCIgEgFIgCgBIAIgBIAAAAIgCgBIgIgCQgEgBgDAAQgEAAgKgFIgEgCQgHgDgHgBQAAgBAAAAQgBAAAAAAQAAAAAAAAQAAgBAAAAIAHAAIAQADIALAEIALADIAOABIAEgBIABAAIgBAAIgJgDQgMgCgFgCIgOgFIgFgBQgCgCgEAAIgGgBQgDgBgCgCQgEgFgCAAQgDAAgDgDIgDAAQgHgDgDgDIgJgCIgDgCIACgBIALACIAKAEIAJAEQADADAHACQAIACAHADIAKACIALADQADACAMABIgCgCQgLgJgDgBIgGgDIgIgCIgJgDIgGgCIgFgCQgDABgEgCIgFgCIgCAAIgFgBQgBAAAAgBQgBAAgBAAQAAAAgBAAQAAgBAAAAIAAgBIgCgCIAFAAQA1AAAoAoQAnAmAAA2QAAATgGASIgCgBQgLgGgMACQgMACgIAJgAArBAIABAAIABABIADAFIAGABQAFABABACIALACQAGABAEADQAAAAAAAAQABABAAAAQAAAAAAgBQAAAAAAAAQABgBAAAAQAAAAAAgBQAAAAAAAAQAAgBAAAAQgCgCgEgBQgBAAAAAAQAAAAgBAAQAAAAgBAAQgBgBAAAAIgEgCIgTgGIgCgBIgDAAIgCgBIAAAAgABKAtIAAABIAJABIAEgBIgBgBIgFAAIgHAAgABIAnIgNAEIAAAAIAGABIAKgCIADgBIABgBIgBgBIgBAAgAAoAkQgBAAAAABQAAAAAAAAQAAAAgBAAQAAAAAAAAIADABQAHAAAFgCQACgBAFAAIAAgBIgBgBIgDAAQgGABgDAAIgBABIABAAIgBAAIAAAAgAAIAeIABACQADACAFgEIAFABQAAAAABAAQAAABABAAQAAAAABAAQAAAAABAAIAEAAIAJgCQACgBAGgBIAAAAIgGgCIgHgCIgDgDIAAABIgBACQgEAEgHgBQgIABgDACgABDgjIgCgBIgEAAQAAAAAAAAQAAAAAAAAQAAAAABAAQAAABAAAAIACAAIADAAIAAAAg");
	this.shape_14.setTransform(40,8.9);

	this.shape_15 = new cjs.Shape();
	this.shape_15.graphics.f("#BD373D").s().p("AA5A9QgKgGgNgCIgMgCIgCAAQgIgCgDgCIgHgCQgFgFgDAAIgJgDIgCgBIgEgBIgGgDQgFgBgCgCIAAgCIAIADQADAAAFADIAIADIAIADIACABIAKAEIAEABIAIACIAJADIAHACIAEAAIAAgBIgNgDIgHgDQgGgDgDgBQgJgDgDgDIAAgBIABgBIADACIAFABQAEAAACADIALADQAHAAAIADIADAAIgFgDIgJgDIgDgCIgFgBIgGgCQAAAAAAAAQgBgBAAAAQgBAAgBAAQAAAAgBAAIAAgBIgKgDIgIgDQgEgBgHgEIgGgBIgFgCIgIgDQgHgCgEgCIgIgFIgDgDQgBgBAAAAQAAAAAAAAQAAgBAAAAQAAAAABAAIAFABQADAAAFAFQAEABAHAFQACABAFAAIAEACQABAAAAAAQABAAAAAAQABAAAAABQABAAAAAAIADABQADAAAEACIAEAAIAGAEIAMADIAEACIAFABIAKAEIAFACIgBgBIgCgBIgFgDQgCgCgEgBIgJgCIgDgBIgDgCQgEgCgEgDIgFgDIgGAAIgHgDQgCAAgGgCIgFgCQgEgDgDAAIgCAAIgFgDIgDgCIgHAAIgEAAQAAAAgBAAQgBAAAAAAQAAAAAAAAQAAAAAAgBIADgCIgCgBIgHgDQgDAAgCgBQgCgBgDAAIgCgBIgCgBQgFgCgCgCIgDAAIgFgCQAAAAgBAAQAAAAgBAAQAAgBgBAAQgBAAgBAAIgHgCIgCAAQgCgJgBgIIAGAAQADADAFAAIAEABQAEABAEADQADAAACACIAHACIAEACQAEgBAGAEIAIADIABABIAHACIAHACQAEABABACIAAABQgDAAgDgBIgFgCIgKgEIgIgDIgMgDIgFgBIAHAEQACABAFAAIAFADQAEAAAGADIAGADIAFACQADABAHABIAKAEIAHAAIAHAEQAEAAADADQAFgBAEADIAEABQAEACAJAAIACgBIAKgCIAJAAQAFABACgBIAAgBIgFgBQgHgDgEAAIgLgEIgHAAIgMgEIgIgCIgEgDIgGgCIgLgDIgHgCIgFgEIgEgBIgDgBQgKgDgEgDIgGgCIgFgBQgFAAgCgBQAAgBgBAAQgBgBAAAAQgBAAAAgBQAAAAgBAAIgJgCIgBAAQgFgDgEABIgCgBIgBgCIgEgBIgHgEQgBgBAAAAQgBgBAAAAQgBgBAAABQgBAAAAAAIgCgBIAAgKIACAAIACABQAEADACgBQAEABAGADIAJAEIAKACQACACAEABQADAAAHADIAOADIADABQACACAFAAIAIABIACABQAKABAEAEIAIABQACAAACACQACACAFACIALABIADABIAJACQAGABAIAHIAHABIAGACIAUAFIAHABIAJABIABABIAAAAQgCAGAAAGIgBAAIgBgBIgDgBIgEgBQgDgBgBgCQgEAAgCgCIgDgBIgEgCIgFgBQgBABgEgDIgFAAIgDgBQgBAAAAAAQgBAAAAAAQgBAAAAAAQAAAAgBAAIgFgCQgFAAgCgBQgEgCgDAAIgFgBIgCgBIgCgBIgEAAIAAABIAAgBIgBAAIAAABIACABIAAAAIABAAIABAAQAAAAABAAQAAAAABABQAAAAABAAQABABABAAIAKAEQADABAGAAQADACAEABIAJAEQADAAAFAFQAGACABACIACACQABAAAAAAQAAABAAAAQAAAAAAABQAAAAAAAAIgBAAIABABIAEACQABADAGAAIABABIADAAIABgBIABAAIgIgEQgBAAAAgBQAAAAgBgBQAAAAAAAAQgBAAAAAAIgHgFIgGgEIgKgGQAAAAgBgBQgBAAAAAAQAAAAgBgBQAAAAAAAAIADgBIAFACIAFADQADABAGADIAIACQACACAFAAIABABIABAAQABAUAQAJIABAAIgHAHIgRAAIgFABQgEADgBAFgAAkAaQACABABAEIAGADIAGADQAAABABAAQAAAAAAABQABAAAAAAQABABABAAQAAABAAAAQgBAAAAAAQAAAAAAAAQAAAAgBAAIABABIABAAIADACIAGABIACAAQACACAGAAIABAAIAAAAIAAgBIgBAAIgCgBIgGgCQAAAAgBAAQAAAAAAgBQgBAAAAAAQgBAAgBAAQAAAAgBAAQAAAAgBAAQAAAAgBgBQAAAAAAAAIACgBIACABIAKABIAEgBIAEgCIgBgEIgCABIgDABIgFAAIgHABIgGgBIgEgDIgCgBQABgBAFACIAIABQABgCAEABIACgCIAAgDIgCgEIgEgEIABgBIAEADIAFAFIACAEIABABIAAAAQAAgBABAAQAAgBgBAAQAAgBAAAAQAAgBgBAAIgCgEQAAAAAAgBQAAAAAAAAQgBAAAAAAQAAgBgBAAIgBgCIAAgBIgFgDQgDgDgEAAQgGgCgFACIgDAAIgJABQgDADgEAAIgFABIgGgBIgCAAIABABIAGADIADAAQAEACACgBQAAAAABAAQAAABAAAAQABAAAAABQAAAAAAABgAApAmIACABIABgBIgBAAIgCgBgAg/gLQABABAFAAIAAAAIgFgBIgDgCIgBAAIgGgDQgDAAgCgBIgFgCIgCAAQABABAAAAQAAAAABABQAAAAABAAQABAAABAAQAAAAABAAQABABAAAAQABAAAAAAQABABAAAAIACAAIAEACIABAAIAFACgAgkgbIABAAIABABIAEACQADADAJADIAKACIAGABIACABIADACIAAAAIAAAAIAEABIABABIAAgBIgCgBIgBgBIAAAAIgBgBIgDAAIgIgEIgEAAIgFgBQgEgEgBABIgGgCIgFgCIgCgBIgBAAIgBAAgAhtgeIAEABQAAAAABAAQAAAAABABQAAAAABAAQABAAABAAIAGACIAEABQABAAAAAAQABABAAAAQABAAAAAAQABAAAAAAIgHgEIgGgCIgEgBIgGABgAgzggIgCgBQgCgCgDAAIAAABIAHACg");
	this.shape_15.setTransform(37,18.5);

	this.shape_16 = new cjs.Shape();
	this.shape_16.graphics.f("#BD373D").s().p("AADACIgEgCIgHgCIAAgBQACgBADABIACABIAHADIADACIAAABQgDAAgDgCg");
	this.shape_16.setTransform(38.1,14.7);

	this.shape_17 = new cjs.Shape();
	this.shape_17.graphics.f("#BD373D").s().p("AAJAEIgHgBIgFgCQgDAAgEgBIgHgDIABgCQACgBAEACIABABIAFACIAEABQACABAIAAIAHACIABABIgBACIgDAAIgFgCg");
	this.shape_17.setTransform(35.3,13.7);

	this.shape_18 = new cjs.Shape();
	this.shape_18.graphics.f("#BD373D").s().p("AAMAFIgEgCIgIAAIgCgBIgCgCIgCAAIgIgCIgCgBIACgBQAAAAAAAAQABgBAAAAQAAAAAAABQABAAAAAAIABAAQAEgBADADIAEACIAAAAIAHAAIADAAQABAAABAAQAAABABAAQAAAAAAAAQABABAAAAIACACIAAABIgEAAg");
	this.shape_18.setTransform(32.6,12.1);

	this.shape_19 = new cjs.Shape();
	this.shape_19.graphics.f("#BD373D").s().p("AAAADIgDgCIgLgDIgDgCIABAAIAGAAIALACIAHACIACAAIAHAEQAAAAAAAAQABABAAAAQAAAAAAAAQAAAAgBAAg");
	this.shape_19.setTransform(38.8,8.7);

	this.shape_20 = new cjs.Shape();
	this.shape_20.graphics.f("#BD373D").s().p("AAIAEIgGAAIgDgCIgGAAIgIgDIgEAAIgBgBQABAAAAgBQAAAAABAAQAAAAAAAAQAAAAAAAAIAFAAQADgBAEADQAGAAABABIAIAAIAGABQAEAAABACIgBACIgLgBg");
	this.shape_20.setTransform(32.1,8.5);

	this.shape_21 = new cjs.Shape();
	this.shape_21.graphics.f("#BD373D").s().p("AgOgEIALACQAEADAFAAIAJAEIgPgBIgCABg");
	this.shape_21.setTransform(30.8,23.2);

	this.shape_22 = new cjs.Shape();
	this.shape_22.graphics.f("#BD373D").s().p("AATANIgHgDQgDgBAAgDIgJgCQAAgDgFAAIAAAAIABACIgDABQgGgBgBgCQgEgBgBAAIgEgCIgMgHQAAAAgBgBQAAAAAAgBQgBAAAAAAQgBgBAAAAIgFgCIAAgBQAHAAADACIABABIAGABIAGACIAEABIAFACIAGACIAFADIACABIAEABQAHABAEAEIADACQAEAAAEADQADADAJAAIAEACIgSAAIgHgDg");
	this.shape_22.setTransform(32.7,22.1);

	this.shape_23 = new cjs.Shape();
	this.shape_23.graphics.f("#BD373D").s().p("AAaANIgKgDIgNgFIgLgEIgKgDIgLgDIAFAEQAAAAAAAAQAAABABAAQAAAAABAAQAAAAABAAQADAAAEABQAFADACAAIAGACIAEADQAKACADAEQAAAAAAABQAAAAAAAAQAAAAgBABQAAAAgBAAIgBgBQgJgCgEgDIgJgEIgKgDQgGgCgEAAIgDADIgCABQgHgKgFgPIABgBIAEACIAGADQAEAEAEAAIAFADIAHADIAKAEQACABAEABIAGACIAMAEIAOAGIAIACIADACIABABIACABQAAAAAAAAQAAAAAAAAQAAABAAAAQAAAAAAAAIgBABg");
	this.shape_23.setTransform(31,19.6);

	this.shape_24 = new cjs.Shape();
	this.shape_24.graphics.f("#BD373D").s().p("AAZAIIgEgBQgFgBgDgCIgHgCQgIAAgJgDQgKgBgDgDQgBAAgBAAQgBgBAAAAQAAgBAAAAQAAAAAAgBIAOACIAGADIAGADIABAAIAHAAIAHAAQAFADADAAIAGABIgBABIgBAEg");
	this.shape_24.setTransform(44.2,17.7);

	this.shape_25 = new cjs.Shape();
	this.shape_25.graphics.f("#BD373D").s().p("AAAADIgCgDIAAgBIACgCIADAAIAAAAIgBACIgCABQADACgCACIgBgBg");
	this.shape_25.setTransform(41.5,21);

	this.shape_26 = new cjs.Shape();
	this.shape_26.graphics.rf(["#FFFFFF","#FEDE3B"],[0,1],-2.6,-2.5,0,-2.6,-2.5,13.4).s().p("AAkB7QgJgGgOgDIgLgBIhSAAIgEABQgXgTgNgaQgNgcAAgfQAAg1AognQAngoA2AAQA3AAAoAoQAnAnAAA1QAAAUgGASIgCgCQgNgHgNAEQgOAEgHAMQgHANAEANQADAOANAHIABABIgIAHIgQAAIgFABQgFACAAAGg");
	this.shape_26.setTransform(39,12.3);

	this.addChild(this.shape_26,this.shape_25,this.shape_24,this.shape_23,this.shape_22,this.shape_21,this.shape_20,this.shape_19,this.shape_18,this.shape_17,this.shape_16,this.shape_15,this.shape_14,this.shape_13,this.shape_12,this.shape_11,this.shape_10,this.shape_9,this.shape_8,this.shape_7,this.shape_6,this.shape_5,this.shape_4,this.shape_3,this.shape_2,this.shape_1,this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(0,0,100.3,52.4);


(lib.Path = function() {
	this.initialize();

	// Layer 1
	this.shape = new cjs.Shape();
	this.shape.graphics.f("#27466D").s().p("AytBiIAAjDMAlbAAAIAADDg");
	this.shape.setTransform(127.3,9.9,1,1,0,0,0,7.4,0);

	this.addChild(this.shape);
}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(0,0,239.7,19.8);


(lib.biker1 = function() {
	this.initialize();

}).prototype = p = new cjs.Container();
p.nominalBounds = new cjs.Rectangle(0,0,0,0);


(lib.out2 = function(mode,startPosition,loop) {
	this.initialize(mode,startPosition,loop,{});

	// mask (mask)
	var mask = new cjs.Shape();
	mask._off = true;
	mask.graphics.p("AwyFLIAAi3MAiWAAFIAAC4g");
	mask.setTransform(112.5,33.7);

	// Layer 2
	this.instance = new lib.Symbol3();
	this.instance.setTransform(115.1,71.5);
	this.instance._off = true;

	this.instance.mask = mask;

	this.timeline.addTween(cjs.Tween.get(this.instance).wait(44).to({_off:false},0).to({y:57.4},10).wait(51));

	// <Path>
	this.instance_1 = new lib.Path("synched",0);
	this.instance_1.setTransform(108.9,57.2,0.918,0.929,0,0,0,113.3,9.1);
	this.instance_1.alpha = 0;
	this.instance_1._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_1).wait(34).to({startPosition:0,_off:false},0).to({alpha:0.75},10).wait(61));

	// ltr_e
	this.instance_2 = new lib.Symbol11();
	this.instance_2.setTransform(220.5,26.4);
	this.instance_2._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_2).wait(18).to({_off:false},0).wait(1).to({x:219.6},0).wait(1).to({x:218.7},0).wait(1).to({x:217.9},0).wait(1).to({x:217},0).wait(1).to({x:216.2},0).wait(1).to({x:215.3},0).wait(1).to({x:214.5},0).wait(80));

	// ltr_n
	this.instance_3 = new lib.Symbol10();
	this.instance_3.setTransform(189.9,26.4);
	this.instance_3._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_3).wait(16).to({_off:false},0).wait(1).to({x:189.3},0).wait(1).to({x:188.8},0).wait(1).to({x:188.2},0).wait(1).to({x:187.6},0).wait(1).to({x:187},0).wait(1).to({x:186.5},0).wait(1).to({x:185.9},0).wait(82));

	// ltr_i
	this.instance_4 = new lib.Symbol9();
	this.instance_4.setTransform(165.7,26.4);
	this.instance_4._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_4).wait(14).to({_off:false},0).wait(1).to({x:165.1},0).wait(1).to({x:164.6},0).wait(1).to({x:164},0).wait(1).to({x:163.4},0).wait(1).to({x:162.8},0).wait(1).to({x:162.3},0).wait(1).to({x:161.7},0).wait(84));

	// ltr_h
	this.instance_5 = new lib.Symbol8();
	this.instance_5.setTransform(142,26.4);
	this.instance_5._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_5).wait(12).to({_off:false},0).wait(1).to({x:141.3},0).wait(1).to({x:140.6},0).wait(1).to({x:139.9},0).wait(1).to({x:139.1},0).wait(1).to({x:138.4},0).wait(1).to({x:137.7},0).wait(1).to({x:137},0).wait(86));

	// ltr_s
	this.instance_6 = new lib.Symbol7();
	this.instance_6.setTransform(112.3,26.4);
	this.instance_6._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_6).wait(10).to({_off:false},0).wait(1).to({x:111.7},0).wait(1).to({x:111.1},0).wait(1).to({x:110.5},0).wait(1).to({x:110},0).wait(1).to({x:109.4},0).wait(1).to({x:108.8},0).wait(1).to({x:108.3},0).wait(88));

	// ltr_t
	this.instance_7 = new lib.Symbol6();
	this.instance_7.setTransform(87.4,26.4);
	this.instance_7._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_7).wait(8).to({_off:false},0).wait(1).to({x:86.6},0).wait(1).to({x:85.9},0).wait(1).to({x:85.2},0).wait(1).to({x:84.5},0).wait(1).to({x:83.8},0).wait(1).to({x:83.1},0).wait(1).to({x:82.4},0).wait(90));

	// ltr_u
	this.instance_8 = new lib.Symbol5();
	this.instance_8.setTransform(59.1,26.7);
	this.instance_8._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_8).wait(6).to({_off:false},0).wait(1).to({x:58.2},0).wait(1).to({x:57.3},0).wait(1).to({x:56.5},0).wait(1).to({x:55.6},0).wait(1).to({x:54.8},0).wait(1).to({x:53.9},0).wait(1).to({x:53.1},0).wait(92));

	// ltr_o
	this.instance_9 = new lib.Symbol4();
	this.instance_9.setTransform(25.2,26.5);
	this.instance_9._off = true;

	this.timeline.addTween(cjs.Tween.get(this.instance_9).wait(4).to({_off:false},0).wait(1).to({x:24.4},0).wait(1).to({x:23.7},0).wait(1).to({x:22.9},0).wait(1).to({x:22.2},0).wait(1).to({x:21.5},0).wait(1).to({x:20.7},0).wait(1).to({x:20},0).wait(94));

}).prototype = p = new cjs.MovieClip();
p.nominalBounds = new cjs.Rectangle(0,0,0,0);

})(lib = lib||{}, images = images||{}, createjs = createjs||{});
var lib, images, createjs;
